### ISSUE TITLE
Use JSON schema to validate configuration

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/plugin-sdk#189]
With https://github.com/cloudquery/plugin-sdk/pull/181, we use custom code to validate our configuration files.

We should consider using a JSON schema file and use [a library to manage validation for us](https://github.com/xeipuuv/gojsonschema).

This should allow us to define the configuration in a declarative way.

Having a JSON schema should also allow code editors to auto complete configuration files based on the schema (though we shouldn't really think about this now)

**Comment by erezrokah** [comment]
Also related https://github.com/cloudquery/plugin-sdk/pull/188

**Comment by yevgenypats** [comment]
I looked into this in the past as well.
I don't think we should do that because mostly it is useful when you want the user to define logic and then execute the validation code. when we have access to the code it's mouch easier to run the validation in code because not everything is available in jsonschema. so we just lose on capabilities and introduce another library.

The big use for jsonschema is really for source/destination plugins but I think it's way to early as well for that. This might also be useful for a future UI to work with jsonschema and build forms but I dont think we should do this now as you suggested.

**Comment by erezrokah** [comment]
Got it, can you share a capability we lose with JSON schema?

Doing validation in code can become quite complex, even for small changes. For example for someone to understand the constraints on our configuration, one needs to follow the logic and branches in https://github.com/cloudquery/plugin-sdk/blob/43a9e5f8e31345f83cf00a1c30e58df00b527f43/specs/source.go#L63.
I don't think it's an issue now. but that logic can be replaced with the following schema:

```json
{
  "type": "object",
  "properties": {
    "kind": { "type": "string", "enum": ["source"] },
    "spec": {
      "type": "object",
      "properties": {
        "name": { "type": "string", "minLength": 1 },
        "registry": { "type": "string", "enum": ["github", "grpc", "local"] },
        "destinations": {
          "type": "array",
          "items": { "type": "string" },
          "minItems": 1
        }
      },
      "if": {
        "properties": { "registry": { "const": "github" } }
      },
      "then": {
        "properties": {
          "version": {
            "type": "string",
            "minLength": 5,
            "maxLength": 14,
            "pattern": "^v(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)$"
          }
        },
        "required": ["version"]
      }
    }
  },
  "required": ["kind", "spec"]
}
```

**Comment by yevgenypats** [comment]
I think it's a classic place where we try to automate something before we have documentation.

The first step needs to be clear documentation of what is required (this should be available regardless what we use for validation). So for someone to understand constraint they should never go for neither jsonschema nor code it should just be documented especially for the parent source and destination spec.

you will always loose capabilities when moving from code->config by design. jsonschema is in draft and actively evolving as well as the same for the jsonschema go library - I used it and it is far from perfect. we should stick to code as long as possible for source and destination specs unless a hard requirement will arise such as: building forms, user defined schema to improve SDK and generate UI automatically.

The current validation code is:
```
	if s.Name == "" {
		return fmt.Errorf("name is required")
	}

	if s.Registry == RegistryGithub {
		if s.Version == "" {
			return fmt.Errorf("version is required")
		}
		if !strings.HasPrefix(s.Version, "v") {
			return fmt.Errorf("version must start with v")
		}
	}

	if len(s.Destinations) == 0 {
		return fmt.Errorf("at least one destination is required")
	}
	return nil
```

I think we are far from having a complex piece of code that we need to introduce jsonschema.

**Comment by erezrokah** [comment]
> The first step needs to be clear documentation of what is required (this should be available regardless what we use for validation). So for someone to understand constraint they should never go for neither jsonschema nor code it should just be documented especially for the parent source and destination spec.

💯 on documenting our configuration constraints.

I think we have different experience with JSON schema, but I haven't used any Go library for it.

I think we can keep this discussion for a future data, as I agree our current config schema is quite simple to validate.

**Comment by erezrokah** [comment]
Closing as wontfix for now
