### ISSUE TITLE
Are json fiels can't be marshaled from strings?

### ISSUE THREAD

**Issue by amanenk** [cloudquery/plugin-sdk#254]
### Describe the bug

Some fields of AWS resources like `aws_route53_traffic_policy_versions` have string fields that are actually JSONs, fields like policy documents.
The check here: https://github.com/cloudquery/plugin-sdk/blob/main/plugins/source_testing.go#L98-L101
does not allow to use strings.

### Expected Behavior

allow string fields to be cased as json.

### Steps to Reproduce

change string column type to json

### Possible Solution

remove the check

### Provider and CloudQuery version

9cd9dab30204baf96ea7e78ba130258cd190eb88

**Comment by hermanschaaf** [comment]
I believe this is expected / correct, since the [check here](https://github.com/cloudquery/plugin-sdk/blob/main/plugins/source_testing.go#L98-L101) is warning you that when a string is sent to a JSON column it will be stored as "JSON" (a string with quotes around it), not queryable JSONB. 

We can support fields returned by the SDK as a string but stored in the DB as JSON column, but the steps then are:
 - Override the column type in codegen to be JSON
 - In the resolver, first unmarshal the string to `map[string]interface{}` before sending it to the channel. Here is an example where this is done: https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/resources/services/mq/brokers_fetch.go#L121-L126

Feel free to check my assumptions here though, it's possible they are outdated :)
