### ISSUE TITLE
feat: Provide a better error when someone references an env variable that doesn't exist

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/plugin-sdk#289]
We support env variables resolution in our config, for example:

```yaml
kind: destination
spec:
  name: postgresql
  version: v1.2.0
  spec:
    connection_string: ${CQ_DSN}
```

However if `CQ_DSN` is not configured we fail with a confusing error:

```
Loading spec(s) from examples
Error: failed to sync source azure: failed to initialize destination plugin client for postgresql: destination configure: failed to call Configure: rpc error: code = Unknown desc = failed to connect to postgresql: failed to connect to `host=/private/tmp user=<user> database=`: dial error (dial unix /private/tmp/.s.PGSQL.5432: connect: no such file or directory)
exit status 1
```

We should provide a clear error message in these cases

**Comment by erezrokah** [comment]
Relevant code in https://github.com/cloudquery/plugin-sdk/blob/93fe5a6fdfe85c076250036253968972a9cc0234/specs/spec_reader.go#L20

**Comment by sankavaala** [comment]
Would like to also add that if the value is set, but is not correct(e.g. incorrect host name or URI etc) it does a fallback ( to localhost, default port, currently logged in user as the user to the database etc ), it would be useful if an error is issued instead of fallback ( or a warning at the least if we still would prefer the fallback)
