### ISSUE TITLE
feat: Add retry logic to plugins download

### ISSUE THREAD

**Issue by erezrokah** [cloudquery/plugin-sdk#291]
Sometimes downloading of plugins fails due to a glitch with GitHub:
https://github.com/cloudquery/cloudquery/actions/runs/3243530449/jobs/5318376371#step:7:9
![image](https://user-images.githubusercontent.com/26760571/195637028-41410d7c-639a-459b-bd99-33057cfe1979.png)

and a simple retry works.

We should add retry logic as to not fail in these cases

**Comment by cychiang** [comment]
Hi @erezrokah I would like to discuss this task with you. I found it a bit difficult to write test cases for downloading an artifact from GitHub. In order to mock a http request, I need to create an interface for `http.Client`, then I can mock a http client for it and start to write test cases for it - it becomes a big task. So I go around the code and what is inside the `download.go` and is basically:

- format url with inputs 
- setup output location and file name
- save file 
- show progressbar

Because create an interface and re-write some code with test cases take times so maybe can go for another way. I'm thinking to improve this part with [go-resty](https://github.com/go-resty/resty) and [httpmock](https://github.com/jarcoal/httpmock) so we can have better handling for downloading files and proper test cases. But not sure is it worth to do it or not. 🤔

**Comment by erezrokah** [comment]
Thanks for the PR @cychiang and pushing this issue forward. I commented on the PR and testing part in https://github.com/cloudquery/plugin-sdk/pull/310#pullrequestreview-1157745326
