### ISSUE TITLE
old docs should be  romoved during docs generation

### ISSUE THREAD

**Issue by amanenk** [cloudquery/plugin-sdk#414]
### Describe the bug

When there are changes in table names, new doc files are added, but old files are not removed, which makes the GitHub action that checks docs fail.

### Expected Behavior

remove all the files from destination directory before generating files

### Steps to Reproduce

create table
generate docs
remove table 
generate docs
run github action

### Provider and CloudQuery version

-

**Comment by hermanschaaf** [comment]
@amanenk It was a deliberate decision to keep deletion of out of the SDK: rather than handling deletion in the docs gen, it should be done as a pre-step before running docs gen. This should be handled already if you use the related makefile command in the cloudquery/cloudquery repo (`make gen-docs`, e.g. for AWS: https://github.com/cloudquery/cloudquery/blob/main/plugins/source/aws/Makefile#L32-L35)

**Comment by yevgenypats** [comment]
Closing per @hermanschaaf , cloudquery should avoid deleting things by default and rather doing this explicitly in a helper/make script

**Comment by amanenk** [comment]
@hermanschaaf i see. I was using go run on Windows. I will try it with Makefile
